---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-gd
    - php-mbstring
    - php-opcache
    - php-pdo-dblib
    - php-pecl-apcu
    - php-pecl-memcached
    - php-pecl-uploadprogress
    - php-pecl-uuid
    - php-pspell
    - php-soap
    - php-twig
    - php-twig-ctwig
    - php-xmlrpc

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm
