---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-gd
    - php-mbstring
    - php-opcache
    - php-pdo-dblib
    - php-pecl-apcu
    - php-pecl-memcached
    - php-pecl-uploadprogress
    - php-pecl-uuid
    - php-pspell
    - php-soap
    - php-twig
    - php-twig-ctwig
    - php-xmlrpc
