---
- name: Ensure postfix is installed (RedHat).
  yum: name=postfix state=installed
  when: ansible_os_family == 'RedHat'

- name: Ensure postfix is installed (Debian).
  apt: name=postfix state=installed
  when: ansible_os_family == 'Debian'

- name: Ensure postfix is started and enabled at boot.
  service: name=postfix state=started enabled=yes
