FROM ubuntu:14.04
# Install Ansible
RUN apt-get install -y software-properties-common git
RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update
RUN apt-get install -y ansible
# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
COPY requirements.yml /etc/ansible/requirements.yml
COPY test.yml /etc/ansible/test.yml
RUN ansible-galaxy install -r /etc/ansible/requirements.yml

