---
- name: Ensure Java is installed.
  pkgng: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"

- name: ensure proc is mounted
  mount: name=/proc fstype=procfs src=proc opts=rw state=mounted

- name: ensure fdesc is mounted
  mount: name=/dev/fd fstype=fdescfs src=fdesc opts=rw state=mounted
