---
language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
script:
  - echo localhost > tests/inventory
  - ansible-playbook -i tests/inventory --syntax-check --list-tasks tests/role.yml
  - ansible-playbook -i tests/inventory --connection=local --sudo -v tests/role.yml
  - ansible-playbook -i tests/inventory --connection=local --sudo --check tests/role.yml
  - >
    ansible-playbook -i tests/inventory --connection=local --sudo tests/role.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
