---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: path={{ item.certificate_file }}
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "vhosts.conf.j2"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Change to Event MPM
  template:
    src: "00-mpm.conf.j2"
    dest: "{{ apache_modules_path }}/00-mpm.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_enable_event_mpm


- name: Activate RemoteIP module
  template:
    src: "90-remoteip.conf.j2"
    dest: "{{ apache_modules_path }}/90-remoteip.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  with_items: "{{ apache_mods_enabled }}"
  when: item == "remoteip"
